export const EXAMPLE_UPDATE = 'EXAMPLE_UPDATE';
export const EXAMPLE_UPDATE_SUCCESS = 'EXAMPLE_UPDATE_SUCCESS';
export const EXAMPLE_UPDATE_FAIL = 'EXAMPLE_UPDATE_FAIL';
export const EXAMPLE_CLEAR_NETWORK_STATE = 'EXAMPLE_CLEAR_NETWORK_STATE';
